blog_bundle_blog_homepage:
    path:     /
    defaults: { _controller: BlogBundleBlogBundle:Page:index }
    requirements:
        _method:  GET

blog_bundle_blog_about:
    path:     /about
    defaults: { _controller: BlogBundleBlogBundle:Page:about }
    requirements:
        _method:  GET
        
blog_bundle_blog_contact:
    path:     /contact
    defaults: { _controller: BlogBundleBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST
        
blog_bundle_blog_show:
    path:  /{id}
    defaults: { _controller: BlogBundleBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+